apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: transparency-logging
build:
  artifacts:
  - image: docker.io/ciphersmaug/tilt-frontend
    context: src/frontend
    docker:
      dockerfile: Dockerfile
  - image: docker.io/ciphersmaug/tilt-user
    context: src/user
    docker:
      dockerfile: Dockerfile
  - image: docker.io/ciphersmaug/tilt-address
    context: src/address
    docker:
      dockerfile: Dockerfile
  - image: docker.io/ciphersmaug/tilt-welcome
    context: src/welcome
    docker:
      dockerfile: Dockerfile
  - image: docker.io/ciphersmaug/tilt-newsletter
    context: src/newsletter
    docker:
      dockerfile: Dockerfile
  - image: docker.io/ciphersmaug/tilt-loadgenerator
    context: src/loadgenerator
    docker:
      dockerfile: Dockerfile
  - image: docker.io/ciphersmaug/tilt-dashboard
    context: src/mining-dashboard
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  #- logging-manifests/*
  - devopsguyfluentd/*
  - otel-manifests/*
  - deployment.yaml