---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-pod
  template:
    metadata:
      labels:
        app: jaeger-pod
    spec:
      containers:
      - name: jaeger-container
        image: jaegertracing/all-in-one
        ports:
        - containerPort: 16686
        - containerPort: 14250
        - containerPort: 14268
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  labels:
    service: jaeger
spec:
  ports:
  - name: dashboard
    port: 16686
    targetPort: 16686
  - name: newotel1
    port: 14250
    targetPort: 14250
  - name: newotel2
    port: 14268
    targetPort: 14268
  selector:
    app: jaeger-pod